FROM apache/airflow:2.9.3-python3.11

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow-providers-docker>=3.8.0" \
    "docker>=6.1.0"

USER root
COPY airflow/dag.py /opt/airflow/dags/dag.py
USER airflow
