services:
  airflow:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/resume-job-matching-system/airflow:latest
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "${AIRFLOW__WEBSERVER__SECRET_KEY}"
    volumes:
      - ../:/project
      - ../airflow:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - airflow_home:/opt/airflow
      - ../data:/data
    ports:
      - "8080:8080"
    command: standalone

volumes:
  airflow_home:
